name: Generate Snake

on:
  schedule:
    # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: To update snake.svg
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/generate-snake-game-from-github-contribution-grid
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: lcopilot
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
